version: '3'

services:
  nginx:
    container_name: nginx
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      - static_volume:/usr/src/app/staticfiles
      - media_volume:/usr/src/app/mediafiles
    depends_on:
      - app
    networks:
      - backend_net

  app:
    container_name: app
    build: .
    command: gunicorn mini_twitter.wsgi:application --reload --bind 0.0.0.0:8000
    volumes:
      - ./:/usr/src/app/
      - static_volume:/usr/src/app/staticfiles
      - media_volume:/usr/src/app/mediafiles
    env_file:
        - ./.env  
    depends_on:
      - db
    networks:
      - backend_net

  db:
    container_name: db
    image: postgres:12.0-alpine
    volumes:
        - ./.postgres_data_prod:/var/lib/postgresql/data/  
    env_file:
        - ./.env.db
    shm_size: 1g
    networks:
      - backend_net
    ports:
      - "5432:5432"
volumes:
  postgres_data:

  static_volume:
  media_volume:
  backups:

networks:
  backend_net:
